exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.12.9'
    hooks:
      - id: ruff
ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
